-- Add missing values to values_catalog
INSERT INTO values_catalog (label) VALUES
('Accountability'),
('Alegria'),
('Ambição'),
('Amor'),
('Atitude'),
('Autodesenvolvimento'),
('Celeridade'),
('Cliente'),
('Coerência'),
('Competitividade'),
('Cooperação'),
('Custo'),
('Diligência'),
('Disciplina'),
('Ecologia'),
('Entusiasmo'),
('Equilíbrio'),
('Espírito de equipe'),
('Família'),
('Fé'),
('Franqueza'),
('Liberdade'),
('Maturidade'),
('Parceria'),
('Praticidade'),
('Realização'),
('Resultado'),
('Servir')
ON CONFLICT (label) DO NOTHING;